version: '3.8'

services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www/src
    depends_on:
      - db

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8008:80"
    volumes:
      - ./src:/var/www/src
    depends_on:
      - app

  db:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./docker/mysql_data:/var/lib/mysql

volumes:
  mysql_data:

